export interface McpToolRegistryEntry {
  key: string;
  group: string;
  displayName: string;
  description: string;
  defaultEnabled: boolean;
  sortOrder: number;
}

export const MCP_TOOL_REGISTRY: McpToolRegistryEntry[] = [
  {
    key: 'check_arc_todo_api_health',
    group: 'system',
    displayName: 'Check API health',
    description: 'Check whether the Arc Todo API is reachable and healthy.',
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    key: 'list_enabled_mcp_tools',
    group: 'system',
    displayName: 'List enabled MCP tools',
    description: 'List MCP tools registered by this server at startup.',
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    key: 'list_organizations',
    group: 'context',
    displayName: 'List organizations',
    description: 'List organizations the authenticated user belongs to.',
    defaultEnabled: true,
    sortOrder: 10,
  },
  {
    key: 'get_organization',
    group: 'context',
    displayName: 'Get organization',
    description: 'Fetch one organization by ID.',
    defaultEnabled: true,
    sortOrder: 11,
  },
  {
    key: 'list_organization_members',
    group: 'context',
    displayName: 'List organization members',
    description: 'List login members of an organization with roles.',
    defaultEnabled: true,
    sortOrder: 12,
  },
  {
    key: 'create_organization_user',
    group: 'context',
    displayName: 'Create organization user',
    description: 'Create a login user and add them to an organization.',
    defaultEnabled: true,
    sortOrder: 13,
  },
  {
    key: 'add_organization_member',
    group: 'context',
    displayName: 'Add organization member',
    description: 'Add an existing login user to an organization by username.',
    defaultEnabled: true,
    sortOrder: 14,
  },
  {
    key: 'list_projects',
    group: 'context',
    displayName: 'List projects',
    description: 'List projects in an organization.',
    defaultEnabled: true,
    sortOrder: 16,
  },
  {
    key: 'create_project',
    group: 'context',
    displayName: 'Create project',
    description: 'Create a project in an organization.',
    defaultEnabled: true,
    sortOrder: 17,
  },
  {
    key: 'get_project',
    group: 'context',
    displayName: 'Get project',
    description: 'Fetch one project by organization and project ID.',
    defaultEnabled: true,
    sortOrder: 18,
  },
  {
    key: 'list_persons',
    group: 'context',
    displayName: 'List persons',
    description: 'List persons globally or within an organization.',
    defaultEnabled: true,
    sortOrder: 20,
  },
  {
    key: 'get_person',
    group: 'context',
    displayName: 'Get person',
    description: 'Fetch one person globally or within an organization.',
    defaultEnabled: true,
    sortOrder: 21,
  },
  {
    key: 'list_tasks',
    group: 'tasks',
    displayName: 'List tasks',
    description: 'List tasks across organizations with optional filters.',
    defaultEnabled: true,
    sortOrder: 20,
  },
  {
    key: 'list_project_tasks',
    group: 'tasks',
    displayName: 'List project tasks',
    description: 'List tasks within a specific project.',
    defaultEnabled: true,
    sortOrder: 21,
  },
  {
    key: 'get_task',
    group: 'tasks',
    displayName: 'Get task',
    description: 'Fetch one task by organization, project, and task ID.',
    defaultEnabled: true,
    sortOrder: 22,
  },
  {
    key: 'create_task',
    group: 'tasks',
    displayName: 'Create task',
    description: 'Create a task in a project.',
    defaultEnabled: true,
    sortOrder: 23,
  },
  {
    key: 'update_task',
    group: 'tasks',
    displayName: 'Update task',
    description: 'Update a task in a project.',
    defaultEnabled: true,
    sortOrder: 24,
  },
  {
    key: 'delete_task',
    group: 'tasks',
    displayName: 'Delete task',
    description: 'Delete a task from a project.',
    defaultEnabled: true,
    sortOrder: 25,
  },
  {
    key: 'list_organization_activity',
    group: 'activity',
    displayName: 'List organization activity',
    description: 'List recent user activity for an organization.',
    defaultEnabled: true,
    sortOrder: 30,
  },
  {
    key: 'list_knowledge',
    group: 'knowledge',
    displayName: 'List knowledge',
    description: 'List knowledge entries for a scope or cross-scope filters.',
    defaultEnabled: true,
    sortOrder: 30,
  },
  {
    key: 'get_knowledge',
    group: 'knowledge',
    displayName: 'Get knowledge',
    description: 'Fetch one knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 31,
  },
  {
    key: 'create_knowledge',
    group: 'knowledge',
    displayName: 'Create knowledge',
    description: 'Create a knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 32,
  },
  {
    key: 'update_knowledge',
    group: 'knowledge',
    displayName: 'Update knowledge',
    description: 'Update a knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 33,
  },
  {
    key: 'delete_knowledge',
    group: 'knowledge',
    displayName: 'Delete knowledge',
    description: 'Delete a knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 34,
  },
  {
    key: 'list_knowledge_attachments',
    group: 'knowledge',
    displayName: 'List knowledge attachments',
    description: 'List attachments for a knowledge entry.',
    defaultEnabled: true,
    sortOrder: 35,
  },
  {
    key: 'upload_knowledge_attachment',
    group: 'knowledge',
    displayName: 'Upload knowledge attachment',
    description: 'Upload a base64-encoded file attachment to a knowledge entry.',
    defaultEnabled: true,
    sortOrder: 36,
  },
  {
    key: 'download_knowledge_attachment',
    group: 'knowledge',
    displayName: 'Download knowledge attachment',
    description: 'Download an attachment and return base64-encoded content.',
    defaultEnabled: true,
    sortOrder: 37,
  },
  {
    key: 'delete_knowledge_attachment',
    group: 'knowledge',
    displayName: 'Delete knowledge attachment',
    description: 'Delete an attachment from a knowledge entry.',
    defaultEnabled: true,
    sortOrder: 38,
  },
  {
    key: 'retrieve_knowledge',
    group: 'rag',
    displayName: 'Retrieve knowledge',
    description:
      'Search indexed Arc Todo knowledge for relevant chunks. Omit organization_id and project_id for general knowledge; provide both for project-scoped search (includes general + project chunks).',
    defaultEnabled: true,
    sortOrder: 40,
  },
];

export const MCP_TOOL_GROUPS = ['system', 'context', 'tasks', 'knowledge', 'rag'] as const;

export type McpToolGroup = (typeof MCP_TOOL_GROUPS)[number];
