export interface McpToolRegistryEntry {
  key: string;
  group: string;
  displayName: string;
  description: string;
  defaultEnabled: boolean;
  sortOrder: number;
}

export const MCP_TOOL_REGISTRY: McpToolRegistryEntry[] = [
  {
    key: 'check_arc_todo_api_health',
    group: 'system',
    displayName: 'Check API health',
    description: 'Check whether the Arc Todo API is reachable and healthy.',
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    key: 'list_enabled_mcp_tools',
    group: 'system',
    displayName: 'List enabled MCP tools',
    description: 'List MCP tools registered by this server at startup.',
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    key: 'list_organizations',
    group: 'context',
    displayName: 'List organizations',
    description: 'List organizations the authenticated user belongs to.',
    defaultEnabled: true,
    sortOrder: 10,
  },
  {
    key: 'get_organization',
    group: 'context',
    displayName: 'Get organization',
    description: 'Fetch one organization by ID.',
    defaultEnabled: true,
    sortOrder: 11,
  },
  {
    key: 'list_organization_members',
    group: 'context',
    displayName: 'List organization members',
    description: 'List login members of an organization with roles.',
    defaultEnabled: true,
    sortOrder: 12,
  },
  {
    key: 'create_organization_user',
    group: 'context',
    displayName: 'Create organization user',
    description: 'Create a login user and add them to an organization.',
    defaultEnabled: true,
    sortOrder: 13,
  },
  {
    key: 'add_organization_member',
    group: 'context',
    displayName: 'Add organization member',
    description: 'Add an existing login user to an organization by username.',
    defaultEnabled: true,
    sortOrder: 14,
  },
  {
    key: 'list_projects',
    group: 'context',
    displayName: 'List projects',
    description: 'List projects in an organization.',
    defaultEnabled: true,
    sortOrder: 16,
  },
  {
    key: 'create_project',
    group: 'context',
    displayName: 'Create project',
    description: 'Create a project in an organization.',
    defaultEnabled: true,
    sortOrder: 17,
  },
  {
    key: 'get_project',
    group: 'context',
    displayName: 'Get project',
    description: 'Fetch one project by organization and project ID.',
    defaultEnabled: true,
    sortOrder: 18,
  },
  {
    key: 'list_persons',
    group: 'context',
    displayName: 'List persons',
    description: 'List persons globally or within an organization.',
    defaultEnabled: true,
    sortOrder: 20,
  },
  {
    key: 'get_person',
    group: 'context',
    displayName: 'Get person',
    description: 'Fetch one person globally or within an organization.',
    defaultEnabled: true,
    sortOrder: 21,
  },
  {
    key: 'list_tasks',
    group: 'tasks',
    displayName: 'List tasks',
    description:
      'List tasks with optional filters. Default include=summary. Rows omit nested project/organization objects. Pass q, limit, and parents_only for duplicate checks. organization_id/project_id UUIDs are optional: use project=ski (acronym) or a friendly task id on another call in this session.',
    defaultEnabled: true,
    sortOrder: 20,
  },
  {
    key: 'list_project_tasks',
    group: 'tasks',
    displayName: 'List project tasks',
    description:
      'List tasks in one project. Leaner than list_tasks (no nested org/project). Pass project=ski (acronym) or slug; UUIDs optional. status, q, limit, and parents_only filter the board so duplicate checks do not pull every status.',
    defaultEnabled: true,
    sortOrder: 21,
  },
  {
    key: 'get_task',
    group: 'tasks',
    displayName: 'Get task',
    description:
      'Fetch one task. Default include=plan (business + plan/code, no QA essay). Friendly IDs like #arc-1 do not need organization_id/project_id. include: summary | plan | qa | full.',
    defaultEnabled: true,
    sortOrder: 22,
  },
  {
    key: 'create_task',
    group: 'tasks',
    displayName: 'Create task',
    description:
      'Create a task in a project. Pass project=ski (acronym) or skill (slug) instead of UUIDs. Optional parent_task_id creates a direct subtask.',
    defaultEnabled: true,
    sortOrder: 23,
  },
  {
    key: 'update_task',
    group: 'tasks',
    displayName: 'Update task',
    description: 'Update a task in a project.',
    defaultEnabled: true,
    sortOrder: 24,
  },
  {
    key: 'delete_task',
    group: 'tasks',
    displayName: 'Delete task',
    description: 'Delete a task from a project.',
    defaultEnabled: true,
    sortOrder: 25,
  },
  {
    key: 'list_task_comments',
    group: 'tasks',
    displayName: 'List task comments',
    description:
      'List comments on a task. Use only when is_bug is true or the user asked. Supports friendly task IDs.',
    defaultEnabled: true,
    sortOrder: 26,
  },
  {
    key: 'add_task_comment',
    group: 'tasks',
    displayName: 'Add task comment',
    description: 'Post a comment on a task. Supports friendly task IDs.',
    defaultEnabled: true,
    sortOrder: 27,
  },
  {
    key: 'list_task_evidence',
    group: 'tasks',
    displayName: 'List task evidence',
    description:
      'List image/video evidence attachments on a task. Use only when is_bug is true or the user asked. Supports friendly task IDs.',
    defaultEnabled: true,
    sortOrder: 28,
  },
  {
    key: 'download_task_evidence',
    group: 'tasks',
    displayName: 'Download task evidence',
    description:
      'Download one task evidence file. Images return as MCP image content for vision; non-images include base64.',
    defaultEnabled: true,
    sortOrder: 29,
  },
  {
    key: 'list_task_history',
    group: 'tasks',
    displayName: 'List task history',
    description:
      'List field-change history for a task (title, description, dueDate, isBug, bugReason). Use only when is_bug is true or the user asked. Supports friendly task IDs.',
    defaultEnabled: true,
    sortOrder: 30,
  },
  {
    key: 'list_organization_activity',
    group: 'activity',
    displayName: 'List organization activity',
    description: 'List recent user activity for an organization.',
    defaultEnabled: true,
    sortOrder: 30,
  },
  {
    key: 'list_knowledge',
    group: 'knowledge',
    displayName: 'List knowledge',
    description: 'List knowledge entries for a scope or cross-scope filters.',
    defaultEnabled: true,
    sortOrder: 30,
  },
  {
    key: 'get_knowledge',
    group: 'knowledge',
    displayName: 'Get knowledge',
    description: 'Fetch one knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 31,
  },
  {
    key: 'create_knowledge',
    group: 'knowledge',
    displayName: 'Create knowledge',
    description: 'Create a knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 32,
  },
  {
    key: 'update_knowledge',
    group: 'knowledge',
    displayName: 'Update knowledge',
    description: 'Update a knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 33,
  },
  {
    key: 'delete_knowledge',
    group: 'knowledge',
    displayName: 'Delete knowledge',
    description: 'Delete a knowledge entry in the selected scope.',
    defaultEnabled: true,
    sortOrder: 34,
  },
  {
    key: 'list_knowledge_attachments',
    group: 'knowledge',
    displayName: 'List knowledge attachments',
    description: 'List attachments for a knowledge entry.',
    defaultEnabled: true,
    sortOrder: 35,
  },
  {
    key: 'upload_knowledge_attachment',
    group: 'knowledge',
    displayName: 'Upload knowledge attachment',
    description: 'Upload a base64-encoded file attachment to a knowledge entry.',
    defaultEnabled: true,
    sortOrder: 36,
  },
  {
    key: 'download_knowledge_attachment',
    group: 'knowledge',
    displayName: 'Download knowledge attachment',
    description: 'Download an attachment and return base64-encoded content.',
    defaultEnabled: true,
    sortOrder: 37,
  },
  {
    key: 'delete_knowledge_attachment',
    group: 'knowledge',
    displayName: 'Delete knowledge attachment',
    description: 'Delete an attachment from a knowledge entry.',
    defaultEnabled: true,
    sortOrder: 38,
  },
  {
    key: 'retrieve_knowledge',
    group: 'rag',
    displayName: 'Retrieve knowledge',
    description:
      'Search indexed Arc Todo knowledge for relevant chunks. Omit organization_id and project_id for general knowledge; provide both for project-scoped search (includes general + project chunks).',
    defaultEnabled: true,
    sortOrder: 40,
  },
  {
    key: 'list_project_diagrams',
    group: 'diagrams',
    displayName: 'List project diagrams',
    description:
      'List Excalidraw diagrams for a project (id, title, thumbnail, timestamps).',
    defaultEnabled: true,
    sortOrder: 50,
  },
  {
    key: 'get_project_diagram',
    group: 'diagrams',
    displayName: 'Get project diagram',
    description: 'Fetch one project diagram including Excalidraw scene_json.',
    defaultEnabled: true,
    sortOrder: 51,
  },
  {
    key: 'create_project_diagram',
    group: 'diagrams',
    displayName: 'Create project diagram',
    description:
      'Create a project Excalidraw diagram with a title and optional scene_json.',
    defaultEnabled: true,
    sortOrder: 52,
  },
  {
    key: 'update_project_diagram',
    group: 'diagrams',
    displayName: 'Update project diagram',
    description: 'Update a project diagram title and/or Excalidraw scene_json.',
    defaultEnabled: true,
    sortOrder: 53,
  },
  {
    key: 'delete_project_diagram',
    group: 'diagrams',
    displayName: 'Delete project diagram',
    description: 'Delete a project Excalidraw diagram.',
    defaultEnabled: true,
    sortOrder: 54,
  },
  {
    key: 'list_project_wireframes',
    group: 'wireframes',
    displayName: 'List project wireframes',
    description:
      'List HTML wireframe prototypes for a project (id, title, timestamps; omits html).',
    defaultEnabled: true,
    sortOrder: 60,
  },
  {
    key: 'get_project_wireframe',
    group: 'wireframes',
    displayName: 'Get project wireframe',
    description: 'Fetch one project wireframe including the HTML document.',
    defaultEnabled: true,
    sortOrder: 61,
  },
  {
    key: 'create_project_wireframe',
    group: 'wireframes',
    displayName: 'Create project wireframe',
    description:
      'Create a project HTML wireframe with a title and optional html document.',
    defaultEnabled: true,
    sortOrder: 62,
  },
  {
    key: 'update_project_wireframe',
    group: 'wireframes',
    displayName: 'Update project wireframe',
    description: 'Update a project wireframe title and/or HTML document.',
    defaultEnabled: true,
    sortOrder: 63,
  },
  {
    key: 'delete_project_wireframe',
    group: 'wireframes',
    displayName: 'Delete project wireframe',
    description: 'Delete a project HTML wireframe.',
    defaultEnabled: true,
    sortOrder: 64,
  },
  {
    key: 'list_project_name_sessions',
    group: 'names',
    displayName: 'List project name sessions',
    description:
      'List naming sessions for a project (id, title, recommendedName, timestamps; omits bulky candidates).',
    defaultEnabled: true,
    sortOrder: 70,
  },
  {
    key: 'get_name_session',
    group: 'names',
    displayName: 'Get name session',
    description:
      'Fetch one naming session including product description, lanes, candidates, evidence, and recommendation.',
    defaultEnabled: true,
    sortOrder: 71,
  },
  {
    key: 'create_name_session',
    group: 'names',
    displayName: 'Create name session',
    description: 'Create a project naming session with a required title.',
    defaultEnabled: true,
    sortOrder: 72,
  },
  {
    key: 'update_name_session',
    group: 'names',
    displayName: 'Update name session',
    description: 'Update naming session title, goal, or product description.',
    defaultEnabled: true,
    sortOrder: 73,
  },
  {
    key: 'add_name_candidates',
    group: 'names',
    displayName: 'Add name candidates',
    description:
      'Add up to 20 name candidates to a session. Source is recorded as MCP.',
    defaultEnabled: true,
    sortOrder: 74,
  },
  {
    key: 'check_name_candidate',
    group: 'names',
    displayName: 'Check name candidate',
    description:
      'Run DNS/RDAP checks for a candidate. Does not register or buy a domain.',
    defaultEnabled: true,
    sortOrder: 75,
  },
  {
    key: 'recommend_name_candidate',
    group: 'names',
    displayName: 'Recommend name candidate',
    description:
      'Recommend a candidate with a decision note. Does not claim legal clearance.',
    defaultEnabled: true,
    sortOrder: 76,
  },
  {
    key: 'get_project_qa_info',
    group: 'qa',
    displayName: 'Get project QA info',
    description:
      'Fetch the project QA info profile (environments, test users, notes). Empty when none is saved yet.',
    defaultEnabled: true,
    sortOrder: 80,
  },
  {
    key: 'update_project_qa_info',
    group: 'qa',
    displayName: 'Update project QA info',
    description:
      'Create or replace the project QA info profile. Omit a field to keep the current value. No password field.',
    defaultEnabled: true,
    sortOrder: 81,
  },
];

export const MCP_TOOL_GROUPS = [
  'system',
  'context',
  'tasks',
  'knowledge',
  'rag',
  'diagrams',
  'wireframes',
  'names',
  'qa',
] as const;

export type McpToolGroup = (typeof MCP_TOOL_GROUPS)[number];
